### ISSUE TITLE
Cycle detected in computation

### ISSUE THREAD

**Issue by ryalb** [infinum/datx#719]
### Used libraries

jsonapi

### Library version(s)

"@datx/core": "^2.4.0","@datx/jsonapi": "^2.4.0"

### Environments with the issue

Chrome

### Environments without the issue

Node v14.18.2

### Current behavior

I am receiving this error below in console intermittently.

```
Uncaught Error: [MobX] Cycle detected in computation ToOne@129.value: function () {
            return this.__rawValue ? this.__getModel(this.__rawValue) : null;
        }
    at die (mobx.esm.js:87:1)
    at ComputedValue.get (mobx.esm.js:1632:1)
    at ObservableObjectAdministration.getObservablePropValue_ (mobx.esm.js:5344:1)
    at ToOne.get (mobx.esm.js:5944:1)
    at getRef (index.esm.js:98:1)
    at DatCell.<anonymous> (index.esm.js:398:1)
    at Object.get getter (index.esm.js:244:1)
    at ComputedValue.computeValue_ (mobx.esm.js:1729:1)
    at ComputedValue.get (mobx.esm.js:1641:1)
    at ObservableObjectAdministration.getObservablePropValue_ (mobx.esm.js:5344:1)
```
Which are the reasons for this to be happening? It seems to be a MobX issue but it is not clear what should I do to fix it when using DatX.

### Expected behavior

No issues in console.

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by DarkoKukovec** [comment]
Hi @ryalb,

Do you by any chance have two models that have ToOne references to each other?
If so, could you post the relevant snippets of the code?
Also, it is possible that the response has references in both directions - maybe the response would be relevant also.

My hunch here is that property a in model A and property b in model B point to each other and therefore create an infinite loop.
